# Generated by Django 5.2.4 on 2025-07-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='goal',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.blogpost'),
        ),
    ]
